mid_project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('recommand/', include('recommand.urls')),
    # path('', include('main.urls')),

    path('admin/', admin.site.urls),
    path('', include('recommand.urls')),
]

recommand/urls.py
from django.urls import path
from . import views # 같은 폴더 내의 views.py를 import

app_name = 'recommand'

urlpatterns = [
    # "127.0.0.1:8000/recommand/" 이후의 URL은 search/urls.py가 handling하도록 만들 예정입니다.
    # path('', views.index, name='index'), # '127.0.0.1:8000/recommand/' 를 받아내도록 만들어줄 것입니다.
    # path('detail/', views.detail ,name='detail'),

    # "127.0.0.1:8000/recommand/" 이후의 URL은 search/urls.py가 handling하도록 만들 예정입니다.
    path('', views.main, name='index'),
    path('recommand/', views.index, name='search'), # '127.0.0.1:8000/recommand/' 를 받아내도록 만들어줄 것입니다.
    path('recommand/detail/', views.detail ,name='detail'),
    # path('autocomplete', views.autocomplete ,name='autocomplete'),
]

recommand/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class ImageSrc(models.Model):
    origin_index = models.IntegerField(default=0)
    src = models.CharField(max_length=300)

    class Meta:
        db_table = 'imgsrc'


class WineName(models.Model):
    origin_index = models.IntegerField(default=0)
    title = models.CharField(max_length=150)
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(3)])

    class Meta:
        db_table = 'winename'

class WineFirst(models.Model):
    origin_index = models.IntegerField(default=0)
    country = models.CharField(max_length=20)
    description = models.CharField(max_length=800)
    designation = models.CharField(max_length=100)
    points = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    province = models.CharField(max_length=50)
    taster_name = models.CharField(max_length=20)
    title = models.CharField(max_length=150)
    variety = models.CharField(max_length=50)
    winery = models.CharField(max_length=100)
    year = models.IntegerField(default=0)
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(3)])
    aging = models.CharField(max_length=150)

    class Meta:
        db_table = 'wine1st'


class WineSecond(models.Model):
    origin_index = models.IntegerField(default=0)
    country = models.CharField(max_length=20)
    description = models.CharField(max_length=800)
    designation = models.CharField(max_length=100)
    points = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    province = models.CharField(max_length=50)
    taster_name = models.CharField(max_length=20)
    title = models.CharField(max_length=150)
    variety = models.CharField(max_length=50)
    winery = models.CharField(max_length=100)
    year = models.IntegerField(default=0)
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(3)])
    aging = models.CharField(max_length=150)

    class Meta:
        db_table = 'wine2nd'


class WineThird(models.Model):
    origin_index = models.IntegerField(default=0)
    country = models.CharField(max_length=20)
    description = models.CharField(max_length=800)
    designation = models.CharField(max_length=100)
    points = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    province = models.CharField(max_length=50)
    taster_name = models.CharField(max_length=20)
    title = models.CharField(max_length=150)
    variety = models.CharField(max_length=50)
    winery = models.CharField(max_length=100)
    year = models.IntegerField(default=0)
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(3)])
    aging = models.CharField(max_length=150)

    class Meta:
        db_table = 'wine3rd'


class CosFirst(models.Model):
    recommand_1 = models.IntegerField(default=0)
    recommand_2 = models.IntegerField(default=0)
    recommand_3 = models.IntegerField(default=0)

    class Meta:
        db_table = 'cos1st'


class CosSecond(models.Model):
    recommand_1 = models.IntegerField(default=0)
    recommand_2 = models.IntegerField(default=0)
    recommand_3 = models.IntegerField(default=0)

    class Meta:
        db_table = 'cos2nd'


class CosThird(models.Model):
    recommand_1 = models.IntegerField(default=0)
    recommand_2 = models.IntegerField(default=0)
    recommand_3 = models.IntegerField(default=0)

    class Meta:
        db_table = 'cos3rd'

recommand/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from .models import *
from .image import scrape
import json
import urllib.parse

# Create your views here.
def main(request):


    return render(request, 'recommand/index.html')


def index(request):

    wine_titles = []
    wine_maps = {}
    for wine in list(WineName.objects.all()):
        wine_maps[wine.title] = wine.grade
        wine_titles.append(wine.title)
    return render(request, 'recommand/recommand.html', {'wine_titles': wine_titles, 'wine_maps':json.dumps(wine_maps)})
    # return render(request, 'recommand/index.html', {'wine_titles': wine_titles})


# title 을 받아서 처리할 함수
def detail(request):

    title = request.POST.get('title')
    grade = int(request.POST.get('grade'))
    print('input : ', title, grade)
    print('keys : ', list(request.POST.keys()))
    main_item = {'aging':'None'}
    recommanded = []

    if grade == 1:
        # main_item = list(WineFirst.objects.filter(aging=title))[0]
        main_item = WineFirst.objects.filter(aging=title)[:1][0]
        recom_idx = CosFirst.objects.get(id=main_item.id)

        recommanded.append(WineFirst.objects.get(id=recom_idx.recommand_1).aging)
        recommanded.append(WineFirst.objects.get(id=recom_idx.recommand_2).aging)
        recommanded.append(WineFirst.objects.get(id=recom_idx.recommand_3).aging)
    elif grade == 2:
        # main_item = list(WineSecond.objects.filter(aging=title))[0]
        main_item = WineSecond.objects.filter(aging=title)[:1][0]
        recom_idx = CosSecond.objects.get(id=main_item.id)

        recommanded.append(WineSecond.objects.get(id=recom_idx.recommand_1).aging)
        recommanded.append(WineSecond.objects.get(id=recom_idx.recommand_2).aging)
        recommanded.append(WineSecond.objects.get(id=recom_idx.recommand_3).aging)
    elif grade == 3:
        # main_item = list(WineThird.objects.filter(aging=title))[0]
        main_item = WineThird.objects.filter(aging=title)[:1][0]
        recom_idx = CosThird.objects.get(id=main_item.id)

        recommanded.append(WineThird.objects.get(id=recom_idx.recommand_1).aging)
        recommanded.append(WineThird.objects.get(id=recom_idx.recommand_2).aging)
        recommanded.append(WineThird.objects.get(id=recom_idx.recommand_3).aging)

    glink = f"https://www.vivino.com/search/wines?q={str(urllib.parse.quote_plus(title))}"

    image = scrape(f"wine {title}  {main_item.variety}")
    # slink, image = scrape(glink)
    # image = '#'


    return render(request, 'recommand/result.html', {'main_item':main_item, 'recommand':recommanded, 'image': image, 'glink': glink})

# def autocomplete(request):
#     grade = request.POST.get('grade')
#     query = request.POST.get('title', None)
#
#     schema = None
#
#     if grade == '1':
#         schema = WineFirst
#     elif grade == '2':
#         schema = WineSecond
#     elif grade == '3':
#         schema = WineThird
#
#     candidate = list(schema.objects.filter(aging__icontains=query)[:10])
#
#     return JsonResponse({'candid': candidate})

def recommand (request):
    return HttpResponse('추천 기능 구현 웹페이지')

recommand/templates/recommand/recommand.html
<!DOCTYPE html>
{% load static %}
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v5.6.13, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v5.6.13, mobirise.com">
  <meta name="twitter:card" content="summary_large_image"/>
  <meta name="twitter:image:src" content="">
  <meta property="og:image" content="">
  <meta name="twitter:title" content="Search">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/logo.png" type="image/x-icon">
  <meta name="description" content="">
  <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>


  <title>Search</title>
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/parallax/jarallax.css' %}">
  <link rel="stylesheet" href="{% static 'assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"></noscript>
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">




</head>
<body>
  <section data-bs-version="5.1" class="menu menu1 cid-tlamt9GY5d" once="menu" id="menu1-m">


    <nav class="navbar navbar-dropdown navbar-expand-lg">
        <div class="container">
            <div class="navbar-brand">

                <span class="navbar-caption-wrap"><a class="navbar-caption text-white text-primary display-7" href="{% url 'recommand:index' %}">Recommand</a></span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true"><li class="nav-item"><a class="nav-link link text-white display-4" href="{% url 'recommand:search' %}">Search By Name<br></a></li>
                    <li class="nav-item"><a class="nav-link link text-white display-4" href="#">Search By Feature<br></a>
                    </li></ul>


            </div>
        </div>
    </nav>
  </section>
  <section data-bs-version="5.1" class="form1 cid-tlvBeLAERa mbr-fullscreen mbr-parallax-background" id="form1-14">




    <div class="mbr-overlay" style="opacity: 0.8; background-color: rgb(255, 255, 255);"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 mx-auto mbr-form" data-form-type="formoid">
                <form action="{% url 'recommand:detail' %}" method="POST" class="mbr-form form-with-styler" data-form-title="Form Name">
                    {% csrf_token %}
                    <div class="row">
                        <div hidden="hidden" data-form-alert="" class="alert alert-success col-12">Thanks for filling out the form!</div>
                        <div hidden="hidden" data-form-alert-danger="" class="alert alert-danger col-12">
                            Oops...! some problem!
                        </div>
                    </div>
                    <div class="dragArea row">
                        <div class="col-12">
                            <h1 class="mbr-section-title mb-4 mbr-fonts-style align-center display-2">
                                <strong>Search By Wine Name</strong></h1>
                        </div>
                        <div class="col-12">
                            <p class="mbr-text mbr-fonts-style mb-5 align-center display-7">Insert the name of wine you like</p>
                        </div>
                        <div class="col-md col-12 form-group mb-3" data-for="grade">
                            <select id='select_grade' class="form-select form-select-lg" name="grade" aria-label="Default select example">
                                <option value="1">High Price ($40~)</option>
                                <option value="2">Middle Price ($25~)</option>
                                <option value="3">Three Price (~$24)</option>
                            </select>
                        </div>
                        <div class="col-md col-12 form-group mb-3" data-for="name">
                            <input type="text" name="title" type="search" list="wine_titles"  aria-label="Search" placeholder="Name to search" class="form-control" id="name-form1-14">
                            <datalist id = "wine_titles" style="width: 100%; height: {{ '2em' }}; overflow: hidden;">
                            {% for title in wine_titles %}
                              <option value="{{title}}"></option>
                            {% endfor %}
                            </datalist>
                        </div>
                        <div class="mbr-section-btn col-12 col-md-auto"><button type="submit" class="btn btn-warning display-4">Search</button></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<section data-bs-version="5.1" class="footer3 cid-s48P1Icc8J" once="footers" id="footer3-p">





    <div class="container">
        <div class="media-container-row align-center mbr-white">


            <div class="row row-copirayt">
                <p class="mbr-text mb-0 mbr-fonts-style mbr-white align-center display-7">
                    © Copyright 2020 Mobirise. All Rights Reserved.
                </p>
            </div>
        </div>
    </div>
</section>
<section class="display-7" style="padding: 0;align-items: center;justify-content: center;flex-wrap: wrap;    align-content: center;display: flex;position: relative;height: 4rem;"><a href="https://mobiri.se/2883266" style="flex: 1 1;height: 4rem;position: absolute;width: 100%;z-index: 1;"><img alt="" style="height: 4rem;" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="></a><p style="margin: 0;text-align: center;" class="display-7">Made with &#8204;</p><a style="z-index:1" href="https://mobirise.com">Mobirise </a></section>
<script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>  <script src="{% static 'assets/parallax/jarallax.js' %}"></script>  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>  <script src="{% static 'assets/ytplayer/index.js' %}"></script>  <script src="{% static 'assets/dropdown/js/navbar-dropdown.js' %}"></script>  <script src="{% static 'assets/theme/js/script.js' %}"></script>
<!-- <script src="assets/formoid/formoid.min.js"></script> -->

<script>
// var search = document.querySelector('#name-form1-14');
// var results = document.querySelector('#wine_titles');
// var templateContent = document.querySelector('#resultstemplate').content;
// search.addEventListener('keyup', function handler(event) {
//     while (results.children.length) results.removeChild(results.firstChild);
//     var inputVal = new RegExp(search.value.trim(), 'i');
//     var clonedOptions = templateContent.cloneNode(true);
//     var set = Array.prototype.reduce.call(clonedOptions.children, function searchFilter(frag, el) {
//  if (inputVal.test(el.textContent) && frag.children.length < 5) frag.appendChild(el);
//         return frag;
//     }, document.createDocumentFragment());
//     results.appendChild(set);
// });
wine_maps = {{ wine_maps | safe }};
grades = ['1', '2', '3'];
$('#name-form1-14').change(function(){
  let curr = wine_maps[$('#name-form1-14').val()];
  console.log($('#name-form1-14').val());
  console.log(curr);
  console.log($('#select_grade').val(curr));
  console.log(grades.indexOf(wine_maps[curr]));
  if(grades.indexOf(wine_maps[curr]) >= 0) {
    $('#select_grade').val(curr).prop("selected", true);
  }
})
</script>

</body>
</html>

recommand/templates/recommand/result.html
<!DOCTYPE html>
{% load static %}
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v5.6.13, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v5.6.13, mobirise.com">
  <meta name="twitter:card" content="summary_large_image"/>
  <meta name="twitter:image:src" content="">
  <meta property="og:image" content="">
  <meta name="twitter:title" content="Detail">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'assets/images/logo.png' %}" type="image/x-icon">
  <meta name="description" content="">


  <title>Detail</title>
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"></noscript>
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">




</head>
<body>
  <section data-bs-version="5.1" class="menu menu1 cid-tlamt9GY5d" once="menu" id="menu1-m">


    <nav class="navbar navbar-dropdown navbar-expand-lg">
        <div class="container">
            <div class="navbar-brand">

                <span class="navbar-caption-wrap"><a class="navbar-caption text-white text-primary display-7" href="{% url 'recommand:index' %}">Recommand</a></span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true"><li class="nav-item"><a class="nav-link link text-white display-4" href="{% url 'recommand:search' %}">Search By Name<br></a></li>
                    <li class="nav-item"><a class="nav-link link text-white display-4" href="#">Search By Feature<br></a>
                    </li></ul>


            </div>
        </div>
    </nav>
  </section>
  <section data-bs-version="5.1" class="features6 cid-tlasXB6xnk" id="features7-u">
    <!---->




    <div class="container">
        <div class="card-wrapper">
            <div class="row align-items-center">
                <div class="col-12 col-lg-6">
                    <div class="image-wrapper">
                        <img src="{{image}}" alt="{{ main_item.title | safe }}">
                    </div>
                </div>
                <div class="col-12 col-lg">
                    <div class="text-box">
                        <h5 class="mbr-title mbr-fonts-style display-2">
                            <strong>{{ main_item.title }}</strong>
                        </h5>
                        <table class="table table-dark">
                            <tbody>
                                <tr>
                                    <th>생산지역</th>
                                    <td>{{ main_item.province }}, {{ main_item.country }}</td>
                                </tr>
                                <tr>
                                    <th>생산연도</th>
                                    <td>{{ main_item.year }}</td>
                                </tr>
                                <tr>
                                    <th>종류</th>
                                    <td>{{ main_item.variety }}</td>
                                </tr>
                                <tr>
                                    <th>점수</th>
                                    <td>{{ main_item.points }}</td>
                                </tr>
                                <tr>
                                    <th>생산자</th>
                                    <td>{{ main_item.winery }}</td>
                                </tr>
                                <tr>
                                    <th colspan="2"><a href="{{ glink | safe }}">쇼핑하러 가기</th>
                                    <!-- <td>{{ glink | safe }}</td> -->
                                </tr>
                            </tbody>
                        </table>
                        <div class="cost">
                            <span class="currentcost mbr-fonts-style pr-2 display-2">${{ main_item.price }}</span>
                            <span class="oldcost mbr-fonts-style display-2"></span>
                        </div>
                        <!-- <div class="mbr-section-btn pt-3"><a href="https://mobiri.se" class="btn btn-warning display-4">Buy Now</a></div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% if recommand %}
<section data-bs-version="5.1" class="content8 cid-tlvE88a78D" id="content8-17">

    <div class="container">
        <div class="row justify-content-center">
            <div class="counter-container col-md-12 col-lg-10">
                <h4 class="mbr-section-title mbr-fonts-style mb-4 display-5">
                    검색하신 와인을 바탕으로 추천하는 와인입니다
                </h4>
                <div class="mbr-text mbr-fonts-style display-7">
                    <ul>
                        {% for item in recommand %}
                        <li>
                            <a href="#" onclick='sendPost(`{{ item }}`);'><strong> {{item | safe}} </strong></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
  function sendPost(item) {
    let form = document.createElement('form');
    form.setAttribute('method', 'post');
    form.setAttribute('action', `{% url 'recommand:detail' %}`);
    document.charset = "UTF-8";
    form.innerHTML += `{% csrf_token %}`;

    let itemField = document.createElement('input');
    itemField.setAttribute('type', 'hidden');
    itemField.setAttribute('name', 'title');
    itemField.setAttribute('value', item);
    form.appendChild(itemField);

    let gradeField = document.createElement('input');
    gradeField.setAttribute('type', 'hidden');
    gradeField.setAttribute('name', 'grade');
    gradeField.setAttribute('value', {{ main_item.grade }});
    form.appendChild(gradeField);

    document.body.appendChild(form);
    form.submit();
  }
</script>
{% endif %}
<section data-bs-version="5.1" class="footer3 cid-s48P1Icc8J" once="footers" id="footer3-s">





    <div class="container">
        <div class="media-container-row align-center mbr-white">


            <div class="row row-copirayt">
                <p class="mbr-text mb-0 mbr-fonts-style mbr-white align-center display-7">
                    © Copyright 2020 Mobirise. All Rights Reserved.
                </p>
            </div>
        </div>
    </div>
</section>
<section class="display-7" style="padding: 0;align-items: center;justify-content: center;flex-wrap: wrap;    align-content: center;display: flex;position: relative;height: 4rem;"><a href="https://mobiri.se/2883266" style="flex: 1 1;height: 4rem;position: absolute;width: 100%;z-index: 1;"><img alt="" style="height: 4rem;" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="></a><p style="margin: 0;text-align: center;" class="display-7">Created with Mobirise &#8204;</p><a style="z-index:1" href="https://mobirise.com/html-builder.html">Free HTML5 Site Generator</a></section><script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>  <script src="{% static 'assets/ytplayer/index.js' %}"></script>  <script src="{% static 'assets/dropdown/js/navbar-dropdown.js' %}"></script>  <script src="{% static 'assets/theme/js/script.js' %}"></script>


</body>
</html>